# Generated by Django 3.1.5 on 2021-01-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('date', models.CharField(max_length=10)),
                ('mid', models.FloatField()),
                ('interpolated', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrencySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('date', models.CharField(max_length=10)),
                ('originalSum', models.FloatField()),
                ('currencySum', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField()),
                ('date', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('unitCost', models.FloatField()),
            ],
        ),
    ]
